config/routes.rb
Advisor::Application.routes.draw do

  root to:'hotels#top_five'
  resources :hotels, only: [:new,:show,:index,:create]
  resources :ratings, only: [:create]
  resources :comments, only: [:create]
  devise_for :users
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :hotel_id, :user_id
  belongs_to :user
  belongs_to :hotel
  validates :content, presence: true, length: { maximum: 250 }
  validates :hotel_id, :user_id, presence: true
end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
  attr_accessible :room_description, :title, :image, :price_for_room,
                  :breakfast_included, :location_attributes, :user_id

  validates :title, presence: true, length:{ maximum:140 }
  validates :room_description, presence: true, length:{ maximum:1500 }
  validates :price_for_room, presence: true, inclusion:{ :in => 0..10000,
    :message => "can not be negative or greater then 10000" }
  validates :breakfast_included, presence: true, inclusion:{ :in => %w(yes no) }
  validates :image, presence: true

  has_one :location
  belongs_to :user
  has_many :ratings
  has_many :raters, :through => :ratings, :source => :users
  has_many :comments

  accepts_nested_attributes_for :location

  mount_uploader :image, ImageUploader

  def average_rating
    ratings = Rating.find_all_by_hotel_id(self.id)
    return 0 if ratings.length == 0
    (ratings.sum{|r| r.rating})/(ratings.length).round(2)
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :city, :country, :state, :street, :hotel_id
  belongs_to :hotel
  validates :city, :country, :state, :street, presence:true, :length=>{ :maximum=>140 }
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :hotel_id, :rating, :user_id

  belongs_to :user
  belongs_to :hotel

  validates :rating, presence: true, inclusion:{ :in => 0..5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :hotels
  has_many :ratings
  has_many :rated_hotels, :through => :ratings, :source => :hotels
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @hotel = Hotel.find_by_id(params[:comment][:hotel_id])
    @comment = current_user.comments.build(params[:comment])
    if @comment.save
      flash[:success] = "You add a comment"
      redirect_to @hotel
    else
      flash[:alert] = "Comment not added"
      redirect_to @hotel
    end
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :new]

  def top_five
    @top_five = Hotel.all.sort_by{ |h| -h.average_rating }.first(5)
  end

  def index
    @hotels = Hotel.paginate(:page => params[:page], :per_page => 5)
  end

  def show
    @hotel = Hotel.find(params[:id])
    @rating = Rating.new
    @comment = Comment.new
    rescue ActiveRecord::RecordNotFound
     logger.error "Attempt to access invalid hotel #{params[:id]}"
      redirect_to hotels_url, notice: 'Invalid hotel'
  end

  def create
    @hotel = current_user.hotels.build(params[:hotel])
    if @hotel.save
      flash[:success] = "Success! Hotel created"
      redirect_to @hotel
    else
      render 'new'
    end
  end

  def new
    @hotel = Hotel.new
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @hotel = Hotel.find_by_id(params[:rating][:hotel_id])
    if @rating = current_user.ratings.find_by_hotel_id(params[:rating][:hotel_id])
      redirect_to @hotel, :notice =>"you already rate this gotel"
    else
      @rating = current_user.ratings.build(params[:rating])
      if @rating.save
        flash[:success] = "Success! you rate this Hotel "
        redirect_to @hotel
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text :
                                  text.scan(regex).join(zero_width_space)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/hotels/_adresses.html.erb
<ul>
    <%= f.fields_for :location_attributes do |location_form| %>
      <li>
        <%= location_form.label :country %>
        <%= location_form.text_field :country %>
      </li>
      <li>
        <%= location_form.label :state %>
        <%= location_form.text_field :state %>
      </li>
      <li>
        <%= location_form.label :city %>
        <%= location_form.text_field :city %>
      </li>
      <li>
        <%= location_form.label :street %>
        <%= location_form.text_field :street %>
       </li>

    <% end %>
</ul>

app/views/hotels/_comment_form.html.erb
<h4>You can leave your comment about this hotel here </h4>
<%= form_for @comment do |f| %>
<%= f.label :content %>
<%= f.text_area :content, rows:"5" %>
<%= f.hidden_field :hotel_id, :value => @hotel.id %>
<br />
<%= f.submit 'Leave comment',:class=>"btn btn-primary"%>
<% end %>

app/views/hotels/_errors.html.erb
<% if @hotel.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@hotel.errors.count, "error") %>.
    </div>
    <ul>
    <% @hotel.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/hotels/_rate_form.html.erb
<h4>Rate this hotel</h4>
<div class="input-append">
	<%= form_for @rating do |f| %>
	<%= f.select(:rating, options_for_select([['1 star', 1], ['2 stars', 2],
	["3 stars", 3], ['4 stars',4], ['5 stars',5]])) %>
	<%= f.hidden_field :hotel_id, :value => @hotel.id %>
	<%= f.submit 'Rate', :class=>"btn btn-success" %>
	<% end %>
</div>

app/views/hotels/index.html.erb
<div class="container" >
<%= link_to "Back", :back %>
	<h3> Hotels</h3>
	<% @hotels.each do |hotel| %>
	<div class="hotels">
		<h4><%= hotel.title %></h4>
		<p>Rating: <%= hotel.average_rating %> stars</p>
        <%= image_tag hotel.image.thumb.url %>
		<p><%= link_to "More details about this hotel", hotel_path(hotel) %></p>
	</div>
	<% end %>
<span><%= will_paginate @hotels %></span>
</div>

app/views/hotels/new.html.erb
<div class="container">
	<%= link_to "Back", :back %>
	<p>
		<h3>
			Fill the form to add your hotel
		</h3>
	</p>

	<%= form_for @hotel, :html => { :multipart => true } do |f| %>
  	<%= render 'errors'  %>
	<%= f.label :image %>
	<%= f.file_field :image %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :room_description %>
    <%= f.text_area(:room_description, rows: 7, maxlength:1500) %>
    <%= f.label :price_for_room %>
    <div class="input-prepend">
        <span class="add-on">
          $
        </span>
        <%= f.text_field :price_for_room, :class=>"input-mini"%>
    </div>
	<div class="breakfast" >
  		<p>Breakfast_included?</p>
  		<%= f.label(:breakfast_included, "Yes", :class=>"radio") %>
  		<%= f.radio_button(:breakfast_included, "yes") %>
  		<%= f.label(:breakfast_included, "No", :class=>"radio") %>
  		<%= f.radio_button(:breakfast_included, "no") %>
	</div>
 	<h4>Addresses:</h4>
 	<%= render "adresses" , f: f%>
 	<%= f.submit "Create new hotel", :class=>"btn btn-large btn-primary"%>
	<% end %>
</div>

app/views/hotels/show.html.erb
<div class="container">
	<%= link_to "Back", :back %>
	<h3><%= @hotel.title %></h3>
	<p>
		Price for room
		<strong>
			<%= number_to_currency(@hotel.price_for_room) %>
		</strong>
	</p>
	<p>
		Breakfast included?
	 	<strong>
	 		<%= @hotel.breakfast_included %>
	 	</strong>
	</p>
	<p class="incenter">
		<%= image_tag @hotel.image.thumb.url %>
	</p>

	<p><%= @hotel.room_description %></p>
	<div id="location">
  		<h5>Location</h5>
		<p>Country: <%= @hotel.location.country %></p>
    	<p>State: <%= @hotel.location.state %></p>
    	<p>City: <%= @hotel.location.city %></p>
    	<p>Street: <%= @hotel.location.street %></p>
	</div>

	<% if current_user %>
 	<%= render 'rate_form' %>
 	<%= render 'comment_form' %>
	<% end %>
	<h4>This hotel have rating <%= @hotel.average_rating %> stars </h4>
	<p>People say about this hotel </p>
    <div class="well">
		<% @hotel.comments.each do |comment| %>
 		<p>User:
 			<strong>
 				<%= comment.user.email %>
 			</strong>
 		<%= time_ago_in_words(comment.created_at) %> ago say:
 		</p>
 		<div id="comment">
 			<%= wrap(comment.content) %></p>
 		</div>
		<% end %>
	</div>
</div>

app/views/hotels/top_five.html.erb
<div class="container" >
	<h1>Top 5 hotels</h1>
	<%= link_to "Other hotels", hotels_path %>
	<% @top_five.each do |top| %>
	<div class="hotels">
 		<h4><%= top.title %></h4>
 		<p>This hotel have rating <%= top.average_rating %> stars</p>
		<%= image_tag top.image.thumb.url %>
		<p><%= link_to "See description", hotel_path(top) %></p>
	</div>
	<% end %>
</div>

app/views/layouts/_header.html.erb
<header >
  <div class="navbar navbar-fixed-top" >
  	 <div class="container">
       <div class="navbar-inner">
   		  <%= link_to 'Advisor', root_path, :class => 'brand' %>
			  <ul class="nav pull-right">
			      <% if user_signed_in? %>
			      <li>
			      	<%= link_to "Add new hotel", new_hotel_path %>
			      </li>
			      <li>
			      	<%= link_to "Sign out", destroy_user_session_path,
			    									    :method=>:delete %>
			      </li>
                  <li>
                  	<p class="navbar-text">
                  		Logged in as <%= current_user.email %>
                  	</p>
                  </li>
                  <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Login
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li>
                      	<%= link_to "Sign in", new_user_session_path %>
                      </li>
                      <li>
                      	<%= link_to "Sign up", new_user_registration_path %>
                      </li>
                    </ul>
                  <% end %>
                  </li>
              </ul>
        </div>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Advisor</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
   <%= render 'layouts/header' %>
	 <div class="container" >
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
     </div>
	<%= yield %>
	<div>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/ratings/create.html.erb
<h1>Ratings#create</h1>
<p>Find me in app/views/ratings/create.html.erb</p>